name: Build Docker Image
description: "Build a Docker image"

outputs:
  image-name:
    description: "Name of image"
    value: ${{ steps.build.outputs.IMAGE_NAME }}
  image-tag:
    description: "Tag with version of branch used to build image "
    value: ${{ steps.build.outputs.IMAGE_TAG }}

runs:
  using: "composite"
  steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Build Docker image
      id: build
      shell: bash
      run: |
        IMAGE_NAME=$(echo '${{ github.repository }}' | awk -F'/' '{print $2}')
        IMAGE_TAG=${{ github.ref_name }}
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
        echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        echo "Building image:$IMAGE_NAME:$IMAGE_TAG"
        docker build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG .
        docker images