name: "ECR Push"
description: "Push a Docker images to Amazon ECR"
inputs:
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  aws-session-token:
    description: "AWS temporary token"
    required: false
  aws-account:
    description: "AWS Account"
    required: true    
  aws-region:
    description: "AWS Region"
    required: true
  repository-name:
    description: "ECR Repository Name"
    required: true
  image-tag:
    description: "Tag for the Docker image"
    required: false
    default: "latest"

runs:
  using: "composite"

  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-session-token: ${{ inputs.aws-session-token }}
        aws-region: ${{ inputs.aws-region }}

    - name: "Login to Amazon ECR"
      shell: bash
      run: |
        aws ecr get-login-password --region ${{ inputs.aws-region }} | \
        docker login --username AWS --password-stdin ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com

    - name: "Push Docker Image to ECR"
      shell: bash
      env:
        ECR_URI=${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
      run: |
        docker tag ${{ inputs.repository-name }}:${{ inputs.image-tag }} $ECR_URI/${{ inputs.repository-name }}:${{ inputs.image-tag }}
        docker push --all-tags $ECR_URI/${{ inputs.repository-name }}:${{ inputs.image-tag }}